"""
Disease Information Database
─────────────────────────────
Wheat (15 classes) + Chilli (8 classes) specific treatment info in EN + UR.
Falls back to __default__ for PlantVillage general classes.
"""

DISEASE_INFO: dict[str, dict] = {

    # ═══════════════════════════════════════════════════════
    # WHEAT — 15 Classes
    # ═══════════════════════════════════════════════════════

    "Healthy": {
        "name_en": "Healthy Plant",
        "name_ur": "صحت مند پودا",
        "severity": "Healthy",
        "desc_en": "The plant appears completely healthy with no signs of disease or pest damage.",
        "desc_ur": "پودا بالکل صحت مند ہے، کسی بیماری یا کیڑے کی علامت نہیں۔",
        "symptoms_en": ["No visible symptoms", "Normal green color", "Healthy growth"],
        "symptoms_ur": ["کوئی علامت نہیں", "سبز رنگ نارمل ہے", "نشوونما ٹھیک ہے"],
        "organic_en": "Continue regular monitoring. Maintain proper irrigation and nutrition.",
        "organic_ur": "باقاعدہ نگرانی جاری رکھیں۔ پانی اور کھاد کا خیال رکھیں۔",
        "chemical_en": "No treatment needed.",
        "chemical_ur": "کسی دوا کی ضرورت نہیں۔",
        "prevention_en": "Crop rotation, clean seeds, proper spacing.",
        "prevention_ur": "فصل بدل کر بوئیں، صاف بیج استعمال کریں، مناسب فاصلہ رکھیں۔",
    },

    "Yellow_Rust": {
        "name_en": "Yellow Rust / Stripe Rust",
        "name_ur": "پیلی زنگ / دھاری زنگ",
        "severity": "High",
        "desc_en": "Yellow Rust is the most common and dangerous wheat disease in Potohar region (Wah, Attock, Rawalpindi). Yellow-orange pustules appear in stripes along leaves.",
        "desc_ur": "پیلی زنگ پوٹھوہار علاقے میں گندم کی سب سے عام اور خطرناک بیماری ہے۔ پتوں پر پیلی دھاریاں بنتی ہیں۔",
        "symptoms_en": ["Yellow-orange pustules in stripes on leaves", "Yellowing of leaf tissue", "Severe cases: complete leaf death", "Most visible in February-March"],
        "symptoms_ur": ["پتوں پر پیلی دھاری دار پھپھوندی", "پتوں کا پیلا پڑنا", "شدید حملے میں پتہ مر جاتا ہے", "فروری-مارچ میں سب سے زیادہ"],
        "organic_en": "Remove severely infected plants. Improve air circulation. Avoid excess nitrogen.",
        "organic_ur": "بری طرح متاثرہ پودے نکال دیں۔ ہوا کی آمدورفت بہتر کریں۔ یوریا کم ڈالیں۔",
        "chemical_en": "Spray Propiconazole 25% EC (1ml/L) or Tebuconazole 25% WG. Spray at first sign and repeat after 14 days.",
        "chemical_ur": "پروپیکونازول 25% (1 ملی/لیٹر) یا ٹیبوکونازول اسپرے کریں۔ پہلی علامت پر اور 14 دن بعد دوبارہ۔",
        "prevention_en": "Use resistant varieties (Barani-17, Arooj-22, Sheraz-23). Sow on time (20 Oct - 20 Nov). Monitor field weekly in Feb-March.",
        "prevention_ur": "مزاحم اقسام لگائیں (بارانی-17، عروج-22، شیراز-23)۔ وقت پر بوائی کریں (20 اکتوبر تا 20 نومبر)۔ فروری-مارچ میں ہفتہ وار نگرانی۔",
    },

    "Brown_Rust": {
        "name_en": "Brown Rust / Leaf Rust",
        "name_ur": "بھوری زنگ / پتہ زنگ",
        "severity": "High",
        "desc_en": "Brown Rust causes small brown-orange pustules scattered on leaves. Very common in Punjab plains.",
        "desc_ur": "بھوری زنگ میں پتوں پر چھوٹے بھورے نارنجی دھبے بکھرے ہوتے ہیں۔ پنجاب میں بہت عام ہے۔",
        "symptoms_en": ["Small round brown-orange pustules on leaf surface", "Pustules scattered randomly", "Yellowing around pustules", "Visible March-April"],
        "symptoms_ur": ["پتوں پر بکھرے ہوئے چھوٹے بھورے دائرے", "دائروں کے گرد پیلا رنگ", "مارچ-اپریل میں نظر آتا ہے"],
        "organic_en": "Remove infected leaves. Maintain field hygiene. Avoid overhead irrigation.",
        "organic_ur": "متاثرہ پتے ہٹائیں۔ کھیت صاف رکھیں۔ اوپر سے پانی نہ دیں۔",
        "chemical_en": "Spray Propiconazole 25% EC or Mancozeb 75% WP at 2g/L. Apply at flag leaf stage.",
        "chemical_ur": "پروپیکونازول 25% یا مینکوزیب 75% (2 گرام/لیٹر) پرچم پتے پر اسپرے کریں۔",
        "prevention_en": "Use certified resistant seed. Crop rotation. Balanced NPK fertilization.",
        "prevention_ur": "تصدیق شدہ مزاحم بیج استعمال کریں۔ فصل بدلیں۔ متوازن کھاد ڈالیں۔",
    },

    "Black_Rust": {
        "name_en": "Black Rust / Stem Rust",
        "name_ur": "کالی زنگ / تنہ زنگ",
        "severity": "Critical",
        "desc_en": "Black Rust is the most destructive wheat disease. Dark brown-black pustules appear on stems and leaves. Can destroy entire crop.",
        "desc_ur": "کالی زنگ گندم کی سب سے تباہ کن بیماری ہے۔ تنے اور پتوں پر سیاہ دھبے بنتے ہیں۔ پوری فصل تباہ ہو سکتی ہے۔",
        "symptoms_en": ["Dark brown to black elongated pustules on stems", "Pustules also on leaves and leaf sheaths", "Stems may break", "Grain shriveled"],
        "symptoms_ur": ["تنے پر سیاہ لمبے دھبے", "پتوں اور غلاف پر بھی", "تنہ ٹوٹ سکتا ہے", "دانہ سکڑ جاتا ہے"],
        "organic_en": "Remove and burn infected plants immediately. Do not compost infected material.",
        "organic_ur": "فوری طور پر متاثرہ پودے نکال کر جلا دیں۔ کھاد میں نہ ملائیں۔",
        "chemical_en": "EMERGENCY: Spray Tebuconazole 25% WG (1g/L) + Propiconazole mixture immediately. Contact local agriculture department.",
        "chemical_ur": "فوری: ٹیبوکونازول 25% (1 گرام/لیٹر) + پروپیکونازول مکسچر اسپرے کریں۔ محکمہ زراعت سے رابطہ کریں۔",
        "prevention_en": "Only use Ug99-resistant varieties. Timely sowing. Regular field scouting.",
        "prevention_ur": "صرف Ug99 مزاحم اقسام استعمال کریں۔ وقت پر بوائی۔ باقاعدہ نگرانی۔",
    },

    "Wheat_Blast": {
        "name_en": "Wheat Blast",
        "name_ur": "گندم بلاسٹ",
        "severity": "Critical",
        "desc_en": "Wheat Blast is an emerging and devastating disease. The entire spike bleaches white before grain fills. Emerging threat in Pakistan.",
        "desc_ur": "گندم بلاسٹ ایک ابھرتی ہوئی خطرناک بیماری ہے۔ دانہ بھرنے سے پہلے پوری بالی سفید ہو جاتی ہے۔",
        "symptoms_en": ["Bleached white spikes (seta)", "Grain not formed or shriveled", "Dark lesions at base of bleached portion", "Appears near grain filling stage"],
        "symptoms_ur": ["سیٹہ مکمل سفید ہو جاتی ہے", "دانہ نہیں بنتا یا سکڑ جاتا ہے", "سفید حصے کی بنیاد پر سیاہ نشان", "دانہ بھرنے کے وقت نظر آتا ہے"],
        "organic_en": "Remove and destroy all infected spikes immediately. Do not save seed from infected crop.",
        "organic_ur": "فوری طور پر تمام متاثرہ بالیاں نکال کر تلف کریں۔ متاثرہ فصل کا بیج نہ رکھیں۔",
        "chemical_en": "Spray Trifloxystrobin + Tebuconazole at heading stage. Report to Plant Protection Department immediately.",
        "chemical_ur": "ٹرائی فلوکسی اسٹروبن + ٹیبوکونازول بالی نکلنے پر اسپرے کریں۔ فوری طور پر محکمہ تحفظ نباتات کو اطلاع دیں۔",
        "prevention_en": "Use certified disease-free seed. Seed treatment with Thiram. Avoid warm humid conditions during heading.",
        "prevention_ur": "بیماری سے پاک سرٹیفائیڈ بیج استعمال کریں۔ تھائیرام سے بیج علاج۔ بالی نکلنے پر گرمی اور نمی سے بچائیں۔",
    },

    "Powdery_Mildew": {
        "name_en": "Powdery Mildew",
        "name_ur": "سفید چورن / پاؤڈری پھپھوندی",
        "severity": "Moderate",
        "desc_en": "White powdery coating on leaves and stems. Common in cool humid weather in Potohar region.",
        "desc_ur": "پتوں اور تنے پر سفید آٹے جیسی تہہ۔ پوٹھوہار کے سرد اور نم موسم میں عام ہے۔",
        "symptoms_en": ["White powdery patches on upper leaf surface", "Affected leaves turn yellow then die", "Stunted plant growth", "Common January-February"],
        "symptoms_ur": ["پتوں کے اوپر سفید آٹے جیسے دھبے", "پتے پیلے پھر مر جاتے ہیں", "پودے کی نشوونما رک جاتی ہے", "جنوری-فروری میں عام"],
        "organic_en": "Spray diluted neem oil (5ml/L) + soap. Improve air circulation. Reduce humidity.",
        "organic_ur": "نیم کا تیل (5 ملی/لیٹر) + صابن اسپرے کریں۔ ہوا کی آمدورفت بہتر کریں۔ نمی کم کریں۔",
        "chemical_en": "Spray Triadimefon 25% WP (1g/L) or Hexaconazole 5% EC at first sign.",
        "chemical_ur": "پہلی علامت پر ٹرائیڈیمیفون 25% (1 گرام/لیٹر) یا ہیگزاکونازول 5% اسپرے کریں۔",
        "prevention_en": "Resistant varieties. Avoid dense sowing. Reduce nitrogen. Good drainage.",
        "prevention_ur": "مزاحم اقسام۔ زیادہ گھنی بوائی نہ کریں۔ نائٹروجن کم کریں۔ نکاسی آب بہتر کریں۔",
    },

    "Septoria": {
        "name_en": "Septoria Leaf Blotch",
        "name_ur": "سیپٹوریا پتہ داغ",
        "severity": "Moderate",
        "desc_en": "Irregular tan-brown blotches with yellow margins on leaves. Spreads rapidly in wet weather.",
        "desc_ur": "پتوں پر بے قاعدہ بھورے دھبے جن کے گرد پیلا کنارہ ہوتا ہے۔ بارش میں تیزی سے پھیلتا ہے۔",
        "symptoms_en": ["Irregular brown-tan lesions on leaves", "Yellow halo around lesions", "Small black dots (pycnidia) in lesions", "Starts from lower leaves"],
        "symptoms_ur": ["پتوں پر بے ڈھنگے بھورے دھبے", "دھبوں کے گرد پیلا دائرہ", "دھبوں میں چھوٹے سیاہ نقطے", "نیچے کے پتوں سے شروع ہوتا ہے"],
        "organic_en": "Remove infected lower leaves. Avoid overhead watering. Improve drainage.",
        "organic_ur": "نیچے کے متاثرہ پتے ہٹائیں۔ اوپر سے پانی نہ دیں۔ نکاسی بہتر کریں۔",
        "chemical_en": "Spray Mancozeb 75% WP (2.5g/L) or Azoxystrobin + Propiconazole.",
        "chemical_ur": "مینکوزیب 75% (2.5 گرام/لیٹر) یا ایزوکسی اسٹروبن + پروپیکونازول اسپرے کریں۔",
        "prevention_en": "Certified disease-free seed. Seed treatment. Crop rotation. Resistant varieties.",
        "prevention_ur": "صاف بیج۔ بیج علاج۔ فصل بدلیں۔ مزاحم اقسام استعمال کریں۔",
    },

    "Smut": {
        "name_en": "Loose Smut / Flag Smut",
        "name_ur": "کانگیاری / ڈھیلی کانگیاری",
        "severity": "High",
        "desc_en": "Grain replaced by black powdery mass. Spreads through infected seed. Loose Smut: black powder replaces entire spike. Flag Smut: black streaks on leaves.",
        "desc_ur": "دانے کی جگہ کالا پاؤڈر بن جاتا ہے۔ متاثرہ بیج سے پھیلتا ہے۔ کانگیاری میں پوری بالی سیاہ، جھنڈا کانگیاری میں پتوں پر دھاریاں۔",
        "symptoms_en": ["Entire spike replaced by black powder (Loose Smut)", "Black streaks on leaves and stems (Flag Smut)", "Affected plants appear before heading", "Powder disperses in wind"],
        "symptoms_ur": ["پوری بالی کالے پاؤڈر میں بدل جاتی ہے", "پتوں اور تنے پر کالی دھاریاں", "بالی نکلنے سے پہلے نظر آتا ہے", "پاؤڈر ہوا میں اڑتا ہے"],
        "organic_en": "Remove infected plants before powder disperses. Burn them away from field.",
        "organic_ur": "پاؤڈر پھیلنے سے پہلے متاثرہ پودے نکالیں۔ کھیت سے دور جلائیں۔",
        "chemical_en": "Seed treatment with Carboxin + Thiram (Vitavax 200 WP) at 2.5g/kg seed before sowing. This is the most effective control.",
        "chemical_ur": "بوائی سے پہلے بیج کو کاربوکسن + تھائیرام (وٹاویکس 200) 2.5 گرام/کلو سے علاج کریں۔ یہ سب سے موثر طریقہ ہے۔",
        "prevention_en": "ALWAYS treat seed before sowing. Use certified smut-free seed. Never save seed from infected crop.",
        "prevention_ur": "ہمیشہ بوائی سے پہلے بیج علاج کریں۔ کانگیاری سے پاک سرٹیفائیڈ بیج استعمال کریں۔ متاثرہ فصل کا بیج کبھی نہ رکھیں۔",
    },

    "Fusarium_Head_Blight": {
        "name_en": "Fusarium Head Blight / Scab",
        "name_ur": "بالی سڑن / فیوزیریم",
        "severity": "High",
        "desc_en": "Partial bleaching of spikes with pink/salmon colored mold. Grains shrivel and may contain mycotoxins harmful to humans.",
        "desc_ur": "بالی کے کچھ حصے سفید اور گلابی/نارنجی پھپھوندی۔ دانے سکڑ جاتے ہیں اور انسانوں کے لیے نقصاندہ زہر ہو سکتا ہے۔",
        "symptoms_en": ["Partial bleaching of spikes", "Pink-salmon mold on spikelets", "Shriveled lightweight grain", "Grain may contain dangerous mycotoxins"],
        "symptoms_ur": ["بالی کا کچھ حصہ سفید", "گلابی پھپھوندی", "ہلکے سکڑے دانے", "دانے میں زہریلا مادہ ہو سکتا ہے"],
        "organic_en": "Harvest early. Do not use infected grain for food or feed. Remove infected heads.",
        "organic_ur": "جلدی کٹائی کریں۔ متاثرہ دانہ کھانے یا چارے میں نہ دیں۔ متاثرہ بالیاں ہٹائیں۔",
        "chemical_en": "Spray Metconazole or Tebuconazole at early flowering (50% anthesis). Timing is critical.",
        "chemical_ur": "پھول آنے کے شروع میں (50% پھول) میٹکونازول یا ٹیبوکونازول اسپرے کریں۔ وقت بہت اہم ہے۔",
        "prevention_en": "Resistant varieties. Avoid corn-wheat rotation (Fusarium host). Seed treatment. Proper drainage.",
        "prevention_ur": "مزاحم اقسام۔ مکئی-گندم چکر سے بچیں۔ بیج علاج۔ اچھی نکاسی آب۔",
    },

    "Leaf_Blight": {
        "name_en": "Helminthosporium Leaf Blight",
        "name_ur": "پتہ جھلساؤ",
        "severity": "Moderate",
        "desc_en": "Brown elongated lesions that cause leaves to blight from tip downward.",
        "desc_ur": "بھورے لمبے دھبے جو پتے کو اوپر سے نیچے کی طرف جھلساتے ہیں۔",
        "symptoms_en": ["Brown elongated lesions", "Leaf tip blight progressing downward", "Dark brown border around lesions", "Severe cases: whole leaf dies"],
        "symptoms_ur": ["بھورے لمبے دھبے", "پتے کی نوک سے جھلسنا شروع", "دھبوں کے گرد گہرا بھورا کنارہ", "شدید حملے میں پورا پتہ مر جاتا ہے"],
        "organic_en": "Remove infected leaves. Improve air circulation. Avoid water stress.",
        "organic_ur": "متاثرہ پتے ہٹائیں۔ ہوا کی آمدورفت بہتر کریں۔ پانی کی کمی سے بچائیں۔",
        "chemical_en": "Spray Mancozeb 75% WP (2g/L) or Copper Oxychloride 50% WP.",
        "chemical_ur": "مینکوزیب 75% (2 گرام/لیٹر) یا کاپر آکسی کلورائیڈ 50% اسپرے کریں۔",
        "prevention_en": "Resistant varieties. Crop rotation. Balanced fertilization.",
        "prevention_ur": "مزاحم اقسام۔ فصل بدلیں۔ متوازن کھاد۔",
    },

    "Tan_Spot": {
        "name_en": "Tan Spot",
        "name_ur": "تین رنگا داغ",
        "severity": "Moderate",
        "desc_en": "Tan-brown oval lesions with yellow halo. Looks like an 'eye'. Common after wet weather.",
        "desc_ur": "آنکھ جیسے بھورے بیضوی دھبے جن کے گرد پیلا دائرہ ہوتا ہے۔ بارش کے بعد عام ہے۔",
        "symptoms_en": ["Tan-brown oval lesion with yellow halo (eyespot)", "Starts on lower leaves", "Lesions merge in severe cases", "Visible after rainy weather"],
        "symptoms_ur": ["آنکھ جیسا بھورا دھبہ پیلے دائرے کے ساتھ", "نچلے پتوں سے شروع", "شدید حملے میں دھبے مل جاتے ہیں", "بارش کے بعد نظر آتا ہے"],
        "organic_en": "Bury or remove wheat stubble. Crop rotation to break disease cycle.",
        "organic_ur": "گندم کی باقیات زمین میں دبائیں یا ہٹائیں۔ بیماری کا چکر توڑنے کے لیے فصل بدلیں۔",
        "chemical_en": "Spray Propiconazole 25% EC (1ml/L) at tillering stage if disease threshold reached.",
        "chemical_ur": "بیماری حد سے بڑھے تو ٹلرنگ مرحلے پر پروپیکونازول 25% (1 ملی/لیٹر) اسپرے کریں۔",
        "prevention_en": "Crop rotation (avoid wheat-wheat). Bury stubble. Certified seed. Resistant varieties.",
        "prevention_ur": "فصل بدلیں (گندم-گندم سے بچیں)۔ باقیات دبائیں۔ سرٹیفائیڈ بیج۔ مزاحم اقسام۔",
    },

    "Common_Root_Rot": {
        "name_en": "Common Root Rot",
        "name_ur": "عام جڑ گلاؤ",
        "severity": "Moderate",
        "desc_en": "Roots turn brown-black and rot. Plants weak and may lodge (fall) in wind.",
        "desc_ur": "جڑیں بھوری یا کالی ہو کر گل جاتی ہیں۔ پودے کمزور اور آندھی میں گر سکتے ہیں (Lodging)۔",
        "symptoms_en": ["Brown-black roots", "Weak stem base", "Plants prone to lodging", "Stunted growth", "Lower leaves die early"],
        "symptoms_ur": ["بھوری کالی جڑیں", "تنے کی بنیاد کمزور", "پودے گرنے کا خطرہ", "نشوونما رکی ہوئی", "نچلے پتے جلدی مرتے ہیں"],
        "organic_en": "Improve drainage. Avoid waterlogging. Seed treatment before sowing.",
        "organic_ur": "نکاسی آب بہتر کریں۔ پانی کھڑا نہ ہونے دیں۔ بوائی سے پہلے بیج علاج کریں۔",
        "chemical_en": "Seed treatment with Thiram + Carboxin (2.5g/kg). Soil drench with Carbendazim if severe.",
        "chemical_ur": "بیج کو تھائیرام + کاربوکسن (2.5 گرام/کلو) سے علاج کریں۔ شدید ہو تو کاربینڈازم سے مٹی تر کریں۔",
        "prevention_en": "Deep tillage. Crop rotation. Avoid compacted waterlogged soils. Balanced potassium.",
        "prevention_ur": "گہری جتائی۔ فصل بدلیں۔ پانی بھرنے اور مٹی سخت ہونے سے بچائیں۔ پوٹاش کھاد متوازن رکھیں۔",
    },

    "Aphid": {
        "name_en": "Wheat Aphid (Tela/Cheepa)",
        "name_ur": "تیلہ / چیپا",
        "severity": "Moderate",
        "desc_en": "Small green-black insects that suck plant sap. They cluster on leaves and spikes causing yellowing. Also spread barley yellow dwarf virus.",
        "desc_ur": "چھوٹے سبز یا کالے کیڑے جو پودے کا رس چوستے ہیں۔ پتوں اور بالیوں پر گچھے بناتے ہیں۔ وائرس بھی پھیلاتے ہیں۔",
        "symptoms_en": ["Clusters of small green/black insects on leaves", "Sticky honeydew on leaves", "Yellowing and curling of leaves", "Stunted plant growth", "More common February-March"],
        "symptoms_ur": ["پتوں پر سبز/کالے کیڑوں کے گچھے", "پتوں پر چپچپا مادہ", "پتوں کا پیلا اور مڑنا", "نشوونما رکنا", "فروری-مارچ میں زیادہ"],
        "organic_en": "Spray neem oil (5ml/L) + soap. Encourage natural predators (ladybirds). Wash plants with water.",
        "organic_ur": "نیم کا تیل (5 ملی/لیٹر) + صابن اسپرے کریں۔ قدرتی دشمن (لیڈی برڈ) کو بڑھاوا دیں۔",
        "chemical_en": "Spray Imidacloprid 70% WS (0.3ml/L) or Chlorpyrifos 40% EC when aphid population exceeds threshold (10 aphids/tiller).",
        "chemical_ur": "جب تیلہ حد سے بڑھے (10 تیلے/ٹلر) تو امیڈاکلوپریڈ 70% (0.3 ملی/لیٹر) یا کلورپائریفوس 40% اسپرے کریں۔",
        "prevention_en": "Monitor field twice weekly in Feb-March. Avoid excessive nitrogen. Plant resistant varieties.",
        "prevention_ur": "فروری-مارچ میں ہفتے میں دو بار کھیت دیکھیں۔ یوریا زیادہ نہ ڈالیں۔ مزاحم اقسام لگائیں۔",
    },

    "Mite": {
        "name_en": "Wheat Mite",
        "name_ur": "گندم کی جوئیں",
        "severity": "Moderate",
        "desc_en": "Tiny spider-like mites cause silvery speckling on leaves. Worst in dry hot conditions.",
        "desc_ur": "بہت چھوٹے مکڑی نما کیڑے پتوں پر چاندی جیسے دھبے بناتے ہیں۔ خشک گرم موسم میں زیادہ نقصان۔",
        "symptoms_en": ["Silvery or bronze speckling on leaves", "Leaves turn pale yellow", "Fine webbing on severe infestation", "Worst in dry conditions"],
        "symptoms_ur": ["پتوں پر چاندی/کانسی جیسے نقطے", "پتے پیلے پڑ جاتے ہیں", "شدید حملے میں باریک جالا", "خشک حالات میں زیادہ"],
        "organic_en": "Spray water to dislodge mites. Neem oil spray (5ml/L). Increase humidity.",
        "organic_ur": "پانی کا اسپرے کریں۔ نیم تیل (5 ملی/لیٹر) اسپرے۔ نمی بڑھائیں۔",
        "chemical_en": "Spray Abamectin 1.8% EC (0.5ml/L) or Spiromesifen. Repeat after 10 days.",
        "chemical_ur": "ابامیکٹن 1.8% (0.5 ملی/لیٹر) یا اسپائیرومیسیفن اسپرے کریں۔ 10 دن بعد دوبارہ۔",
        "prevention_en": "Avoid dust on plants. Proper irrigation. Avoid pesticides that kill natural mite predators.",
        "prevention_ur": "پودوں پر دھول نہ پڑنے دیں۔ مناسب آبپاشی۔ ایسی دوائیں نہ استعمال کریں جو قدرتی دشمن مار دیں۔",
    },

    "Stem_Fly": {
        "name_en": "Wheat Stem Fly (Tanah Makhi)",
        "name_ur": "تنہ مکھی",
        "severity": "Moderate",
        "desc_en": "Larvae bore into stems causing Dead Heart (central shoot dies) in vegetative stage or White Ear in reproductive stage.",
        "desc_ur": "لاروا تنے میں گھس کر ڈیڈ ہارٹ (بڑھوتری میں درمیانی ٹہنی مرتی ہے) یا وائٹ ایئر (بالی سفید ہو جاتی ہے) پیدا کرتا ہے۔",
        "symptoms_en": ["Dead Heart: central tiller dies, pulls out easily", "White Ear: spike bleaches without grain", "Small fly visible on plants", "More common in early sown crop"],
        "symptoms_ur": ["ڈیڈ ہارٹ: درمیانی ٹہنی مر جاتی ہے، آسانی سے نکل آتی ہے", "وائٹ ایئر: بالی سفید بغیر دانے", "پودوں پر چھوٹی مکھی نظر آتی ہے", "جلدی بوئی فصل میں زیادہ"],
        "organic_en": "Avoid early sowing before Oct 20. Remove dead hearts. Crop rotation.",
        "organic_ur": "20 اکتوبر سے پہلے بوائی نہ کریں۔ ڈیڈ ہارٹ نکالیں۔ فصل بدلیں۔",
        "chemical_en": "Seed treatment with Imidacloprid 70% WS (7ml/kg seed) before sowing. This is most effective.",
        "chemical_ur": "بوائی سے پہلے بیج کو امیڈاکلوپریڈ 70% (7 ملی/کلو بیج) سے علاج کریں۔ یہ سب سے موثر ہے۔",
        "prevention_en": "Timely sowing (20 Oct - 20 Nov). Seed treatment mandatory. Crop rotation. Early detection.",
        "prevention_ur": "وقت پر بوائی (20 اکتوبر تا 20 نومبر)۔ بیج علاج لازمی۔ فصل بدلیں۔ جلدی پتہ لگائیں۔",
    },

    # ═══════════════════════════════════════════════════════
    # CHILLI — 8 Classes
    # ═══════════════════════════════════════════════════════

    "Anthracnose": {
        "name_en": "Chilli Anthracnose",
        "name_ur": "مرچ انتھراکنوز",
        "severity": "High",
        "desc_en": "Fungal disease causing dark sunken lesions on fruits and leaves. Major post-harvest problem.",
        "desc_ur": "پھلوں اور پتوں پر سیاہ گہرے دھبے۔ کٹائی کے بعد بڑا مسئلہ ہے۔",
        "symptoms_en": ["Dark sunken circular lesions on fruits", "Orange-pink spore masses in lesions", "Lesions on leaves too", "Fruit rot in storage"],
        "symptoms_ur": ["پھلوں پر سیاہ گول گہرے دھبے", "دھبوں میں نارنجی گلابی پاؤڈر", "پتوں پر بھی دھبے", "ذخیرے میں پھل سڑنا"],
        "organic_en": "Remove infected fruits immediately. Copper-based spray. Avoid overhead irrigation.",
        "organic_ur": "متاثرہ پھل فوری ہٹائیں۔ تانبے پر مبنی اسپرے۔ اوپر سے پانی نہ دیں۔",
        "chemical_en": "Spray Azoxystrobin 23% SC (1ml/L) or Carbendazim 50% WP (1g/L). Apply preventively.",
        "chemical_ur": "ایزوکسی اسٹروبن 23% (1 ملی/لیٹر) یا کاربینڈازم 50% (1 گرام/لیٹر) احتیاطی طور پر اسپرے کریں۔",
        "prevention_en": "Use certified disease-free seed. Crop rotation (avoid solanaceous crops). Good drainage. Harvest at right time.",
        "prevention_ur": "بیماری سے پاک بیج۔ فصل بدلیں (ٹماٹر، بینگن سے بچیں)۔ اچھی نکاسی۔ صحیح وقت پر کٹائی۔",
    },

    "Leaf_Curl_Virus": {
        "name_en": "Chilli Leaf Curl Virus",
        "name_ur": "مرچ پتہ مروڑ وائرس",
        "severity": "High",
        "desc_en": "Viral disease spread by whitefly. Leaves curl upward, distort, and plant stunts. No cure — prevention is key.",
        "desc_ur": "سفید مکھی سے پھیلنے والی وائرل بیماری۔ پتے اوپر کو مڑ جاتے ہیں، پودہ رک جاتا ہے۔ علاج نہیں — روک تھام ضروری ہے۔",
        "symptoms_en": ["Leaves curl upward or inward", "Leaf distortion and crumpling", "Stunted plant growth", "Reduced fruit set", "Spread by whitefly"],
        "symptoms_ur": ["پتے اوپر یا اندر کو مڑ جاتے ہیں", "پتوں کا بگڑنا اور سکڑنا", "پودے کی نشوونما رکنا", "کم پھل آنا", "سفید مکھی سے پھیلتا ہے"],
        "organic_en": "Remove infected plants immediately. Control whitefly with yellow sticky traps and neem oil.",
        "organic_ur": "متاثرہ پودے فوری ہٹائیں۔ پیلے چپچپے جال اور نیم تیل سے سفید مکھی کنٹرول کریں۔",
        "chemical_en": "No cure for virus. Control whitefly vector: spray Imidacloprid 17.8% SL (0.5ml/L) or Thiamethoxam.",
        "chemical_ur": "وائرس کا علاج نہیں۔ سفید مکھی کنٹرول کریں: امیڈاکلوپریڈ 17.8% (0.5 ملی/لیٹر) یا تھائیامیتھوکسم اسپرے۔",
        "prevention_en": "Use virus-resistant varieties. Reflective mulch to repel whitefly. Control whitefly from seedling stage. Use virus-free transplants.",
        "prevention_ur": "وائرس مزاحم اقسام استعمال کریں۔ سفید مکھی بھگانے کے لیے چمکیلی پلاسٹک۔ پنیری سے سفید مکھی کنٹرول کریں۔",
    },

    "Veinal_Mottle_Virus": {
        "name_en": "Chilli Veinal Mottle Virus",
        "name_ur": "مرچ رگ داغ وائرس",
        "severity": "High",
        "desc_en": "Viral disease causing yellow mottling along leaf veins. Spread by aphids.",
        "desc_ur": "رگوں کے ساتھ پیلا دھبہ وائرس۔ تیلے سے پھیلتا ہے۔",
        "symptoms_en": ["Yellow-green mottling along leaf veins", "Leaf distortion", "Stunted growth", "Reduced yield", "Spread by aphids"],
        "symptoms_ur": ["پتوں کی رگوں کے ساتھ پیلا دھبہ", "پتوں کا مڑنا", "نشوونما رکنا", "پیداوار کم ہونا", "تیلے سے پھیلتا ہے"],
        "organic_en": "Remove infected plants. Control aphids with neem oil. Use yellow sticky traps.",
        "organic_ur": "متاثرہ پودے ہٹائیں۔ نیم تیل سے تیلہ کنٹرول۔ پیلے جال لگائیں۔",
        "chemical_en": "No virus cure. Control aphid vector: Imidacloprid or Acetamiprid spray.",
        "chemical_ur": "وائرس کا علاج نہیں۔ تیلہ کنٹرول: امیڈاکلوپریڈ یا ایسیٹامیپریڈ اسپرے۔",
        "prevention_en": "Use certified virus-free seed/transplants. Control aphids from day one. Roguing (remove infected plants).",
        "prevention_ur": "وائرس سے پاک بیج/پنیری۔ شروع سے تیلہ کنٹرول۔ متاثرہ پودے نکالتے رہیں۔",
    },

    "Leaf_Spot": {
        "name_en": "Chilli Leaf Spot (Cercospora)",
        "name_ur": "مرچ پتہ داغ",
        "severity": "Moderate",
        "desc_en": "Circular brown-gray spots with lighter centers on leaves. Leaves drop prematurely.",
        "desc_ur": "پتوں پر گول بھورے-سرمئی دھبے جن کا مرکز ہلکا ہوتا ہے۔ پتے جلدی گرتے ہیں۔",
        "symptoms_en": ["Circular spots with gray center and brown border", "Spots on leaves, stems and fruits", "Premature leaf drop", "Defoliation in severe cases"],
        "symptoms_ur": ["سرمئی مرکز اور بھورے کنارے والے گول دھبے", "پتوں، تنے اور پھلوں پر دھبے", "پتوں کا جلدی گرنا", "شدید حملے میں پودہ ننگا ہو جاتا ہے"],
        "organic_en": "Remove infected leaves. Copper oxychloride spray (3g/L). Improve air circulation.",
        "organic_ur": "متاثرہ پتے ہٹائیں۔ کاپر آکسی کلورائیڈ (3 گرام/لیٹر) اسپرے۔ ہوا کی آمدورفت بہتر کریں۔",
        "chemical_en": "Spray Mancozeb 75% WP (2g/L) or Chlorothalonil 75% WP (2g/L) at 14-day intervals.",
        "chemical_ur": "مینکوزیب 75% (2 گرام/لیٹر) یا کلوروتھیلونل 75% 14 دن کے وقفے سے اسپرے کریں۔",
        "prevention_en": "Crop rotation. Avoid dense planting. Drip irrigation preferred. Remove crop debris.",
        "prevention_ur": "فصل بدلیں۔ گھنی بوائی نہ کریں۔ ڈرپ آبپاشی بہتر ہے۔ فصل کی باقیات ہٹائیں۔",
    },

    "Whitefly": {
        "name_en": "Chilli Whitefly (Safaid Makhi)",
        "name_ur": "سفید مکھی",
        "severity": "Moderate",
        "desc_en": "Tiny white flying insects on leaf undersides. Suck sap and transmit viruses (Leaf Curl).",
        "desc_ur": "پتوں کے نیچے سفید اڑنے والے چھوٹے کیڑے۔ رس چوستے اور وائرس پھیلاتے ہیں (پتہ مروڑ)۔",
        "symptoms_en": ["White tiny flies under leaves", "Sticky honeydew on leaves", "Sooty mold on honeydew", "Yellowing leaves", "Transmits Leaf Curl Virus"],
        "symptoms_ur": ["پتوں کے نیچے سفید چھوٹے کیڑے", "پتوں پر چپچپا مادہ", "کالی پھپھوندی", "پتے پیلے", "پتہ مروڑ وائرس پھیلاتا ہے"],
        "organic_en": "Yellow sticky traps. Neem oil spray (5ml/L). Reflective mulch. Natural enemies (Encarsia parasitoid).",
        "organic_ur": "پیلے چپچپے جال۔ نیم تیل (5 ملی/لیٹر) اسپرے۔ چمکیلی پلاسٹک۔",
        "chemical_en": "Spray Imidacloprid 17.8% SL (0.5ml/L) or Spiromesifen. Rotate insecticides to prevent resistance.",
        "chemical_ur": "امیڈاکلوپریڈ 17.8% (0.5 ملی/لیٹر) یا اسپائیرومیسیفن اسپرے کریں۔ مختلف ادویات باری باری استعمال کریں۔",
        "prevention_en": "Monitor regularly. Install yellow sticky traps early. Use reflective mulch. Avoid excessive nitrogen.",
        "prevention_ur": "باقاعدہ نگرانی کریں۔ جلدی پیلے جال لگائیں۔ چمکیلی پلاسٹک استعمال کریں۔ یوریا زیادہ نہ ڈالیں۔",
    },

    "Yellowish": {
        "name_en": "Chilli Yellowish (Nutritional/Viral)",
        "name_ur": "مرچ پیلاہٹ",
        "severity": "Moderate",
        "desc_en": "General yellowing of chilli leaves. Can be due to nitrogen deficiency, iron chlorosis, waterlogging, or viral infection.",
        "desc_ur": "مرچ کے پتوں کا پیلا پڑنا۔ نائٹروجن کمی، آئرن کلوروسس، پانی کھڑا رہنا یا وائرس کی وجہ سے۔",
        "symptoms_en": ["General leaf yellowing", "Starts from older leaves (nutrient)", "Or young leaves (viral/iron)", "Stunted growth"],
        "symptoms_ur": ["پتوں کا پیلا پڑنا", "پرانے پتوں سے شروع (غذائی کمی)", "یا نئے پتوں سے (وائرس/آئرن)", "نشوونما رکنا"],
        "organic_en": "Check soil nutrients. Apply compost. Ensure proper drainage. Check for virus symptoms.",
        "organic_ur": "مٹی کے غذائی اجزاء چیک کریں۔ کمپوسٹ ڈالیں۔ نکاسی آب یقینی بنائیں۔ وائرس علامات چیک کریں۔",
        "chemical_en": "Soil test first. Apply NPK as needed. Iron chelate spray for iron deficiency (1g/L FeSO4).",
        "chemical_ur": "پہلے مٹی ٹیسٹ کریں۔ NPK ضرورت کے مطابق۔ آئرن کمی کے لیے آئرن کیلیٹ اسپرے (1 گرام/لیٹر FeSO4)۔",
        "prevention_en": "Soil testing before planting. Balanced fertilization. Good drainage. Virus control.",
        "prevention_ur": "بوائی سے پہلے مٹی ٹیسٹ۔ متوازن کھاد۔ اچھی نکاسی۔ وائرس کنٹرول۔",
    },

    "Damping_Off": {
        "name_en": "Chilli Damping Off",
        "name_ur": "مرچ جڑ سڑن (پنیری مرض)",
        "severity": "High",
        "desc_en": "Fungal disease killing seedlings at or near soil level. Major nursery problem.",
        "desc_ur": "پنیری مرحلے میں مٹی کی سطح کے قریب پودے مر جاتے ہیں۔ نرسری میں بڑا مسئلہ۔",
        "symptoms_en": ["Seedlings collapse at soil level", "Dark water-soaked stem base", "Rapid death of seedlings", "Circular patches of dead seedlings in nursery"],
        "symptoms_ur": ["پنیری مٹی کی سطح پر گر جاتی ہے", "تنے کی بنیاد کالی اور گیلی", "پنیری تیزی سے مرتی ہے", "نرسری میں گول دائروں میں مردہ پنیری"],
        "organic_en": "Use sterile nursery mix. Avoid overwatering. Improve drainage. Trichoderma soil treatment.",
        "organic_ur": "صاف نرسری مکسچر استعمال کریں۔ زیادہ پانی نہ دیں۔ نکاسی بہتر کریں۔ ٹرائیکوڈرما مٹی علاج۔",
        "chemical_en": "Drench nursery with Captan 50% WP (2g/L) or Metalaxyl + Mancozeb before sowing.",
        "chemical_ur": "بوائی سے پہلے نرسری کو کیپٹان 50% (2 گرام/لیٹر) یا میٹالیکسل + مینکوزیب سے بھگوئیں۔",
        "prevention_en": "Use raised beds. Steam sterilize nursery soil. Avoid dense sowing. Good drainage. Seed treatment.",
        "prevention_ur": "اونچی کیاریاں بنائیں۔ نرسری مٹی بھاپ سے صاف کریں۔ گھنی بوائی نہ کریں۔ اچھی نکاسی۔ بیج علاج۔",
    },

    # ═══════════════════════════════════════════════════════
    # DEFAULT — PlantVillage general classes fallback
    # ═══════════════════════════════════════════════════════
    "__default__": {
        "name_en": "Plant Disease Detected",
        "name_ur": "پودے میں بیماری",
        "severity": "Moderate",
        "desc_en": "A plant disease has been detected. Please consult your local agriculture extension officer for specific treatment advice.",
        "desc_ur": "پودے میں بیماری پائی گئی ہے۔ مزید معلومات کے لیے اپنے مقامی زرعی ماہر سے رابطہ کریں۔",
        "symptoms_en": ["Visible disease symptoms on plant", "Consult local agriculture department"],
        "symptoms_ur": ["پودے پر بیماری کی علامات نظر آ رہی ہیں"],
        "organic_en": "Remove affected plant parts. Improve growing conditions. Contact local agriculture extension.",
        "organic_ur": "متاثرہ حصے ہٹائیں۔ بڑھوتری کے حالات بہتر کریں۔ محکمہ زراعت سے رابطہ کریں۔",
        "chemical_en": "Consult local agriculture extension officer for specific fungicide/pesticide recommendation.",
        "chemical_ur": "مخصوص دوا کے لیے مقامی زرعی ماہر سے مشورہ کریں۔",
        "prevention_en": "Crop rotation, certified seeds, proper irrigation, balanced fertilization.",
        "prevention_ur": "فصل بدلیں، سرٹیفائیڈ بیج، مناسب آبپاشی، متوازن کھاد۔",
    },
}
